inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/Documentation:
  Exclude:
    - 'lib/libssh/key.rb' # Documented in ext
    - 'spec/**'

Metrics:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/libssh_ruby/extconf.rb'
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Exclude:
    - 'Rakefile'
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
