inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/Documentation:
  Exclude:
    - 'lib/libssh/key.rb' # Documented in ext

Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/libssh_ruby/extconf.rb'
Style/HashSyntax:
  Exclude:
    - 'Rakefile'
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/SignalException:
  EnforcedStyle: only_raise
