language: ruby
sudo: required
dist: trusty  # Require libssh >= 0.6.0
addons:
  apt:
    packages:
      - libssh-dev
rvm:
  - 2.2
  - 2.3.0
  - ruby-head
before_install:
  - gem install --no-rdoc --no-ri bundler
matrix:
  allow_failures:
    - rvm: ruby-head
